### ISSUE TITLE
MetroRapid initials not capitalized in stop names

### ISSUE THREAD

**Issue by barbeau** [Hillsborough-Transit-Authority/hart-data#12]
For most, if not all, of the stops visited by the MetroRapid route, the initials for Metrorapid are shown as "Mr" instead of "MR".  For example, see:
- stop_id 7581 - http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_7581
- stop_id 7800 - http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_7800
- stop_id 6904 - http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_6904

**Comment by StPierreP** [comment]
@barbeau @haneys This issue has been brought to the attention of Tim Wicktor. He plans on changing the query to fix the issue. Should be fixed in November 2015.

Known case issues are:
Mr should be MR
Uatc should be UATC
Us should be US
Mlk should be MLK

Please advise if you would like to keep this ticket open in the mean time or close it. Thank you.

**Comment by barbeau** [comment]
Thanks @StPierreP!  I'll go ahead and close it if its being resolved internally at HART.  We can reopen in Nov. if its still a problem then.
